### ISSUE TITLE
Wrong start position

### ISSUE THREAD

**Issue by error414** [skyfpv/FlowState#3]
Sometimes after click to "restart" copter has wrong start position, Under table :). It seem that there are problem with collision model with table. 

See https://youtu.be/jidTlegHt_E?t=3

Win10 V1803 / I5-3320M / HD4000 / 16GB / SSD 500GB / Frsky X7 connected as HID

**Comment by skyfpv** [comment]
Think I've got a fix for this. The quad's position is set on the first frame of the game. Unfortunately, the frame rate is not yet stable at this point, and depending on hardware, the physics will freak out for a bit. There is a frame rate settling period during which the quad's velocity is set to 0. The fix for now should be to force the position of the quad until the frame rate settles down. This will be fixed in the next version
